README.md: Fix HACS magic install link
kamiKAC/leaf2mqtt pull request #2
Opened 2024-01-04 02:11 UTC by reedy

2024-01-11 07:51 UTC, compuguy commented
Looks like the manifest also needs to be edited:
`manifest for yp87/leaf2mqtt:6 not found: manifest unknown: manifest unknown`

2024-01-11 12:38 UTC, reedy commented
> Looks like the manifest also needs to be edited: `manifest for yp87/leaf2mqtt:6 not found: manifest unknown: manifest unknown`

It looks like it's pretty much a doable find and replace throughout the repo.... Untested though

2024-05-20 23:14 UTC, kamiKAC requested changes
Please correct double '>' in repository.json

2024-05-20 23:14 UTC, kamiKAC commented on repository.json
> +  "maintainer": "kamiKAC <kamiKAC@users.noreply.github.com>>"
double '>' at the end
please correct

2024-05-21 00:33 UTC, reedy commented on repository.json
> +  "maintainer": "kamiKAC <kamiKAC@users.noreply.github.com>>"
Done

2024-05-21 07:21 UTC, merged